export const routines = [
  {
    name: 'New Routine',
    numberOfDays: 4,
    duration: '70',
    calories: '100',
    sets: '12',
    image: 'https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHNxdWF0fGVufDB8fDB8fHww',
    days: [
      {
        name: 'Push Day',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 1,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 2,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 2',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 3,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 4,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 3',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 5,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 6,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 4',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 7,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 8,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
    ],
  },
  {
    name: 'New Routine 2',
    numberOfDays: 4,
    duration: '70',
    calories: '100',
    sets: '12',
    image: 'https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHNxdWF0fGVufDB8fDB8fHww',
    days: [
      {
        name: 'Push Day',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 9,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 10,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 2',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 11,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 12,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 3',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 13,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 14,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
      {
        name: 'Push Day 4',
        duration: '70',
        calories: '100',
        sets: '12',
        exercises: [
          {
            name: 'Bench Press',
            id: 15,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
          {
            name: 'Bench Press',
            id: 16,
            sets: 3,
            reps: 10,
            weight: 50,
            rest: 60,
          },
        ],
      },
    ],
  }
]